services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - "variables.env"
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "5173:5173"
